zuul:
  routes:
    get:
      path: /auth/**
      url: https://kimixbond-api.herokuapp.com/api/auth
    links:
      path: /users/**
      url: https://kimixbond-api.herokuapp.com/api/users
    images:
      path: /base/**
      url: https://kimixbond-api.herokuapp.com/api

eureka:
  client:
    enabled: false