zuul:
  routes:
    abbas:
      path: /abbas/**
      url: http://httpbin.org/get
    auth:
      path: /jokes/**
      url: https://api.chucknorris.io/jokes/random
    users:
      path: /users/**
      url: https://kimixbond-api.herokuapp.com/api/users
    base:
      path: /base/**
      url: https://kimixbond-api.herokuapp.com/api
  ribbon:
    ConnectTimeout: 120000
    ReadTimeout: 120000
    eager-load:
      enabled: true

eureka:
  client:
    enabled: false