zuul:
  sslHostnameValidationEnabled: false
  routes:
    abbas:
      path: /abbas/**
      url: http://httpbin.org/get
    auth:
      path: /jokes/**
      url: http://api.chucknorris.io/jokes/random
    users:
      path: /users/**
      url: https://kimixbond-api.herokuapp.com/api/users
    base:
      path: /base/**
      url: http://kimixbond-api.herokuapp.com/api
  ribbon:
    ConnectTimeout: 120000
    isSecure: true
    ReadTimeout: 120000
    eager-load:
      enabled: 
    # TrustStore: classpath:keystore.jks
    # TrustStorePassword : password

eureka:
  client:
    enabled: false

# server:
#   ssl:
#     enabled: true
#     key-store: classpath:keystore.jks
#     key-store-password: password
#     key-alias: selfsigned
#     keyStoreType: JKS