zuul:
  sslHostnameValidationEnabled: false
  routes:
    abbas:
      path: /abbas/**
      url: https://httpbin.org/get
    auth:
      path: /jokes/**
      url: https://api.chucknorris.io/jokes/random
    users:
      path: /users/**
      url: https://kimixbond-api.herokuapp.com/api/users
    base:
      path: /base/**
      url: http://kimixbond-api.herokuapp.com/api


eureka:
  client:
    enabled: false


# zuul:
#   routes:
#     my-service:
#       path: /my-service/**
#       serviceId: my-service

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/